### ISSUE TITLE
Python version support above Python 3.6.x

### ISSUE THREAD

**Issue by julienmartinelli** [clonker/PyNumTools#4]
Hello, 

Would it be possible to update this package so that versions of python >=3.7 work? Mac OS monterey users cannot use (easily) prior versions of python and the conda installations has specifications "- pynumtools -> python[version='3.6.*|>=3.6,<3.7.0a0']"

Thank you.

**Comment by clonker** [comment]
Cheers Julien,

I will look into it tomorrow but you can already try the following:
clone the repository and install with `pip install .` while in the directory of the clone.

Best!

**Comment by julienmartinelli** [comment]
Thank you. 
Regarding pip, that was my first attempt. But I got a massive stacktrace having to do with Eigen/SparseCore not being found... 
```
    In file included from /private/var/folders/77/n2k4zf3941q3x7m1ldxd3zcm0000gn/T/pip-req-build-ib8erd4s/cpp/lgmres.h:35:
    /private/var/folders/77/n2k4zf3941q3x7m1ldxd3zcm0000gn/T/pip-req-build-ib8erd4s/cpp/util.h:17:10: fatal error: 'Eigen/SparseCore' file not found
    #include <Eigen/SparseCore>
             ^~~~~~~~~~~~~~~~~~
```

**Comment by clonker** [comment]
Yeah sorry for the late response! Things are currently hectic. You can install eigen and then compile or wait for me to overhaul the installation process. Which part of the package are you interested in anyways?

**Comment by julienmartinelli** [comment]
I will give it a try. I am trying to benchmark this reaction inference algorithm : https://github.com/rmjiang7/bayes_reactive_sindy . It relies on readdy_learn, which itself relies on PyNumTools.......

**Comment by clonker** [comment]
can you check again with pip? it should be fixed

**Comment by clonker** [comment]
cool, no problem! closing this issue then
